version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
      day: wednesday
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: wednesday
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
