[environment.properties]
artifactsDir = "out/jreleaser/assemble/sdkman/archive"

[project]
name = "sdkman"
description = "SDKMAN! native extensions"
longDescription = "Supplementary native extension binaries to replace SDKMAN! bash functions."
website = "https://github.com/sdkman/sdkman-native-cli"
authors = ["Marco Vermeulen", "Oliver Weiler"]
license = "Apache 2.0"

[project.extraProperties]
inceptionYear = 2021

[platform.replacements]
osx-x86_64 = "x86_64-apple-darwin"
osx-aarch_64 = "aarch64-apple-darwin"
linux-x86_64 = "x86_64-unknown-linux-gnu"
linux-aarch_64 = "aarch64-unknown-linux-gnu"
windows-x86_64 = "x86_64-pc-windows-msvc"

[release.github]
overwrite = true

[release.github.changelog]
formatted = "ALWAYS"
format = "- {{commitShortHash}} {{commitTitle}}"
preset = "conventional-commits"

[release.github.changelog.contributors]
format = "- {{contributorName}}{{#contributorUsernameAsLink}} ({{.}}){{/contributorUsernameAsLink}}"

[assemble.archive.sdkman]
active = "ALWAYS"
formats = ["ZIP"]
attachPlatform = true

[[assemble.archive.sdkman.fileSets]]
input = "target/{{ osPlatformReplaced }}/release"
output = "bin"
includes = ["sdkman{.exe,}"]

[[assemble.archive.sdkman.fileSets]]
input = "."
includes = ["LICENSE"]

[distributions.sdkman]
type = "BINARY"

[distributions.sdkman.executable]
windowsExtension = "exe"

[[distributions.sdkman.artifacts]]
path = "{{artifactsDir}}/{{distributionName}}-{{projectVersion}}-aarch64-apple-darwin.zip"
platform = "osx-aarch_64"

[[distributions.sdkman.artifacts]]
path = "{{artifactsDir}}/{{distributionName}}-{{projectVersion}}-x86_64-apple-darwin.zip"
platform = "osx-x86_64"

[[distributions.sdkman.artifacts]]
path = "{{artifactsDir}}/{{distributionName}}-{{projectVersion}}-x86_64-pc-windows-msvc.zip"
platform = "windows-x86_64"

[[distributions.sdkman.artifacts]]
path = "{{artifactsDir}}/{{distributionName}}-{{projectVersion}}-x86_64-unknown-linux-gnu.zip"
platform = "linux-x86_64"

[[distributions.sdkman.artifacts]]
path = "{{artifactsDir}}/{{distributionName}}-{{projectVersion}}-aarch64-unknown-linux-gnu.zip"
platform = "linux-aarch_64"
